### ISSUE TITLE
Définir l'alphabet

### ISSUE THREAD

**Issue by SuperFola** [Drarig29/TuringMachine#2]
Peut-être qu'il faudrait pouvoir définir l'alphabet utilisé, comme ça la classe `Turing` sait quel caractère blanc utiliser quand il faut agrandir le ruban et peut aussi savoir quand il y a un caractère inconnu (pour indiquer une erreur de construction de programme au runtime).

**Comment by Drarig29** [comment]
Oui je l'avais fait au début mais je n'en avais pas l'utilité. Bonne idée en effet :)
